services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./PythonApi/db/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - app-network

  frontend:
    build: ./Front-End
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    command: npm run dev -- --host 0.0.0.0
    develop:
      watch:
        - path: ./Front-End/src
          action: sync # sync = copia arquivo sem rebuildar
          target: /app/src
        - path: ./Front-End/package.json
          action: rebuild # rebuild = reconstrói a imagem

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
      - ./PythonApi:/workspace
    entrypoint: >
      sh -c "ollama serve &
             sleep 5 &&
             ollama pull phi3:mini &&
             ollama pull nomic-embed-text &&
             ollama create bitzar-rag -f /workspace/Modelfile &&
             wait"
    networks:
      - app-network
    develop:
      watch:
        - path: ./PythonApi/Modelfile
          action: rebuild # rebuild ao mudar o Modelfile

  csharp-api:
    build: ./Api
    container_name: csharp-api
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - ollama
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network
    develop:
      watch:
        - path: ./Api
          action: rebuild

  python-api:
    build: ./PythonApi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OLLAMA_HOST: ${OLLAMA_HOST}
    depends_on:
      - postgres
      - ollama
    networks:
      - app-network
    develop:
      watch:
        - path: ./PythonApi
          action: sync # sync = copia sem rebuildar
          target: /app
          ignore:
            - __pycache__
            - "*.pyc"
            - .venv
        - path: ./PythonApi/requirements.txt
          action: rebuild # rebuild só se mudar dependências

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
